package model;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.dbutils.DbUtils;
import org.hsqldb.server.Servlet;

public class DatabaseDAO extends Servlet {

	private static final long serialVersionUID = 1L;

	private Connection connection;
	private Statement statement;

	private final String connectionString = "jdbc:hsqldb:file:${user.home}/i377/Team09d/db;shutdown=true";

	public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		try {
			connection = DriverManager.getConnection(connectionString);
			statement = connection.createStatement();
			createTables();
		} catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			DbUtils.closeQuietly(statement);
			DbUtils.closeQuietly(connection);
		}
		response.getWriter().println("success!");
	}

	@Override
	public void init() throws ServletException {
		try {
			Class.forName("org.hsqldb.jdbcDriver");
		} catch (ClassNotFoundException e) {
			throw new RuntimeException(e);
		}
	}

	public void createTables() throws SQLException {
		createTableRiigiAdminYksus();
		createTableRiigiAdminYksuseLiik();
		createTableVoimalikAlluvus();
		createTableAdminAlluvus();
	}

	public void insertTestData() throws SQLException {
		insertTestDataRiigiAdminYksus();
		insertTestDataRiigiAdminYksuseLiik();
		insertTestDataVoimalikAlluvus();
		insertTestDataAdminAlluvus();
	}

	private void createTableRiigiAdminYksus() throws SQLException {
		statement
				.executeUpdate("CREATE TABLE RIIGI_ADMIN_YKSUS ("
						+ "riigi_admin_yksus_ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
						+ "avaja                VARCHAR(32) NOT NULL,"
						+ "avatud               DATE NOT NULL,"
						+ "muutja               VARCHAR(32) NOT NULL,"
						+ "muudetud             DATE NOT NULL,"
						+ "sulgeja              VARCHAR(32),"
						+ "suletud              DATE NOT NULL,"
						+ "kood                 VARCHAR(20),"
						+ "nimetus              VARCHAR(100),"
						+ "kommentaar           LONG VARCHAR,"
						+ "alates               DATE NOT NULL,"
						+ "kuni                 DATE NOT NULL,"
						+ "riigi_admin_yksuse_lik_id INTEGER NOT NULL,"
						+ "PRIMARY KEY (riigi_admin_yksus_ID), "
						+ "FOREIGN KEY (riigi_admin_yksuse_lik_id) REFERENCES RIIGI_ADMIN_YKSUSE_LIIK ON DELETE RESTRICT);");
	}

	private void insertTestDataRiigiAdminYksus() throws SQLException {
		statement
				.executeUpdate("INSERT INTO RIIGI_ADMIN_YKSUS("
						+ "avaja, avatud, muutja, muudetud, sulgeja, suletud, kood, nimetus, kommentaar, alates, kuni, riigi_admin_yksuse_lik_id) VALUES("
						+ "'Välek', '12-12-12', 'Vibulane', '12-12-12', 'Aleksei', '12-12-12', 'TTTT', 'TEST', 'Testandmed riigi admin üksus', '12-12-11', '12-12-12', '1'); ");
	}

	private void createTableRiigiAdminYksuseLiik() throws SQLException {
		statement
				.executeUpdate("CREATE TABLE RIIGI_ADMIN_YKSUSE_LIIK ("
						+ "riigi_admin_yksuse_lik_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
						+ "avaja                VARCHAR(32) NOT NULL,"
						+ "avatud               DATE NOT NULL,"
						+ "muutja               VARCHAR(32) NOT NULL,"
						+ "muudetud             DATE NOT NULL,"
						+ "sulgeja              VARCHAR(32),"
						+ "suletud              DATE NOT NULL,"
						+ "kood                 VARCHAR(10) NOT NULL,"
						+ "nimetus              VARCHAR(100) NOT NULL,"
						+ "kommentaar           LONG VARCHAR,"
						+ "alates               DATE NOT NULL,"
						+ "kuni                 DATE NOT NULL,"
						+ "PRIMARY KEY (riigi_admin_yksuse_lik_id));");
	}

	private void insertTestDataRiigiAdminYksuseLiik() throws SQLException {
		statement.executeUpdate("INSERT INTO RIIGI_ADMIN_YKSUSE_LIIK("
						+ "avaja, avatud, muutja, muudetud, sulgeja, suletud, kood, nimetus, kommentaar, alates, kuni) VALUES("
						+ "'Välek', '12-12-12', 'Vibulane', '12-12-12', 'Aleksei', '12-12-12', 'TTTT', 'TEST', 'Testandmed riigi admin üksuse liik', '12-12-11', '12-12-12');");
	}

	private void createTableVoimalikAlluvus() throws SQLException {
		statement
				.executeUpdate("CREATE TABLE VOIMALIK_ALLUVUS ("
						+ "voimalik_alluvus_id  INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
						+ "avaja                VARCHAR(32) NOT NULL,"
						+ "avatud               DATE NOT NULL,"
						+ "muutja               VARCHAR(32) NOT NULL,"
						+ "muudetud             DATE NOT NULL,"
						+ "sulgeja              VARCHAR(32),"
						+ "suletud              DATE NOT NULL,"
						+ "riigi_admin_yksuse_lik_id INTEGER NOT NULL,"
						+ "kommentaar           LONG VARCHAR,"
						+ "PRIMARY KEY (voimalik_alluvus_id),"
						+ "FOREIGN KEY (riigi_admin_yksuse_lik_id) REFERENCES RIIGI_ADMIN_YKSUSE_LIIK ON DELETE RESTRICT);");
	}
	
	private void insertTestDataVoimalikAlluvus() throws SQLException {
		statement.executeUpdate("INSERT INTO VOIMALIK_ALLUVUS("
						+ "avaja, avatud, muutja, muudetud, sulgeja, suletud, riigi_admin_yksuse_lik_id, kommentaar) VALUES("
						+ "'Välek', '12-12-12', 'Vibulane', '12-12-12', 'Aleksei', '12-12-12', '1', 'Testandmed VOIMALIK ALLUVUS');");
	}

	private void createTableAdminAlluvus() throws SQLException {
		statement
				.executeUpdate("CREATE TABLE ADMIN_ALLUVUS  ("
						+ "admin_alluvus_id     INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
						+ "avaja                VARCHAR(32) NOT NULL,"
						+ "avatud               DATE NOT NULL,"
						+ "muutja               VARCHAR(32) NOT NULL,"
						+ "muudetud             DATE NOT NULL,"
						+ "sulgeja              VARCHAR(32),"
						+ "suletud              DATE NOT NULL,"
						+ "alates               CHAR(18),"
						+ "kuni                 CHAR(18),"
						+ "kommentaar           CHAR(18),"
						+ "PRIMARY KEY (admin_alluvus_id));");
	}
	
	private void insertTestDataAdminAlluvus() throws SQLException {
		statement.executeUpdate("INSERT INTO ADMIN_ALLUVUS("
				+ "avaja, avatud, muutja, muudetud, sulgeja, suletud, alates, kuni, kommentaar) VALUES("
				+ "'Välek', '12-12-12', 'Vibulane', '12-12-12', 'Aleksei', '12-12-12', '12-12-11', '12-12-12', 'Testandmed admin alluvus');");
	}
}
